{
 "title": "Netology-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "description": "CPULA 1/5/15",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "description": "количество свободной оперативной памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "graph",
   "description": "количество места на файловой системе",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{device=\"/dev/nvme0n1p2\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"} / node_filesystem_size_bytes{device=\"/dev/nvme0n1p2\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}) * 100"
    }
   ]
  }
 ]
}